resolver: ghc-9.2
packages:
  - .
  - sandbox
extra-deps:
  - extra-1.7.8
  - clock-0.8
  - split-0.2.3.4
  - random-1.2.1
  - splitmix-0.1.0.4
ghc-options :
  "$everything": -Wall
system-ghc: true
allow-newer: true
